### groupby command

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('movies.csv')

In [3]:
data.head(5)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

-> groupby command is applicable only for categorical data

In [4]:
genre = data.groupby('Genre')

In [5]:
genre.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [6]:
genre.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [7]:
genre.max()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [8]:
# find the top three movies based on the genre
data.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [9]:
# find the genre with the highest IMDM rating
data.groupby('Genre')['IMDB_Rating'].sum().head(3)

Genre
Action       1367.3
Adventure     571.5
Animation     650.3
Name: IMDB_Rating, dtype: float64

In [10]:
# find the genre with the highest IMDM rating
data.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [11]:
# find the director with most popularity
data.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [12]:
# Find the highest rated movie of each genre (Wrong answer)
data.groupby('Genre')['IMDB_Rating'].sum().sort_values(ascending=False).head()

Genre
Drama        2299.7
Action       1367.3
Comedy       1224.7
Crime         857.8
Biography     698.6
Name: IMDB_Rating, dtype: float64

In [13]:
# Find the highest rated movie of each genre
data.groupby('Genre')['IMDB_Rating'].max()

Genre
Action       9.0
Adventure    8.6
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.2
Drama        9.3
Family       7.8
Fantasy      8.1
Film-Noir    8.1
Horror       8.5
Mystery      8.4
Thriller     7.8
Western      8.8
Name: IMDB_Rating, dtype: float64

-> .sum() : this function just count all the numerical values

// IMP

In [16]:
# find the number of movies done by each actor 
data.groupby('Star1').count()['Series_Title'].sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [17]:
# find the total number of groups
len(data.groupby('Genre'))

14

In [18]:
# find items in each group
data.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [19]:
# find the starting first data
data.groupby('Genre').size().head()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
dtype: int64

In [20]:
# find the starting last data
data.groupby('Genre').size().tail()

Genre
Film-Noir     3
Horror       11
Mystery      12
Thriller      1
Western       4
dtype: int64

In [21]:
# accessing data from particular index
data.groupby('Genre')

In [22]:
data.describe()

           Runtime  IMDB_Rating   No_of_Votes         Gross   Metascore
count  1000.000000  1000.000000  1.000000e+03  1.000000e+03  843.000000
mean    122.891000     7.949300  2.736929e+05  1.282781e+08   77.971530
std      28.093671     0.275491  3.273727e+05  2.011110e+08   12.376099
min      45.000000     7.600000  2.508800e+04  1.305000e+03   28.000000
25%     103.000000     7.700000  5.552625e+04  5.012919e+06   70.000000
50%     119.000000     7.900000  1.385485e+05  3.953432e+07   79.000000
75%     137.000000     8.100000  3.741612e+05  1.615997e+08   87.000000
max     321.000000     9.300000  2.343110e+06  9.366622e+08  100.000000

In [23]:
data.groupby('Director').value_counts()

Director             Series_Title                Released_Year  Runtime  Genre      IMDB_Rating  Star1               No_of_Votes  Gross        Metascore
Aaron Sorkin         The Trial of the Chicago 7  2020           129      Drama      7.8          Eddie Redmayne      89896        853090410.0  77.0         1
Abdellatif Kechiche  La vie d'Adèle              2013           180      Drama      7.7          Léa Seydoux         138741       2199675.0    89.0         1
Abhishek Kapoor      Kai po che!                 2013           130      Drama      7.7          Amit Sadh           32628        1122527.0    40.0         1
Adam McKay           The Big Short               2015           130      Biography  7.8          Christian Bale      362942       70259870.0   81.0         1
Akira Kurosawa       Kagemusha                   1980           180      Drama      8.0          Tatsuya Nakadai     32195        66363801.0   84.0         1
                                                                                                                                                           ..
Yôjirô Takita        Okuribito                   2008           130      Drama      8.1          Masahiro Motoki     48582        1498210.0    68.0         1
Zack Snyder          300                         2006           117      Action     7.6          Gerard Butler       732876       210614939.0  52.0         1
                     Watchmen                    2009           162      Action     7.6          Jackie Earle Haley  500799       107509799.0  56.0         1
Zaza Urushadze       Mandariinid                 2013           87       Drama      8.2          Lembit Ulfsak       40382        144501.0     73.0         1
Zoya Akhtar          Gully Boy                   2019           154      Drama      8.0          Vijay Varma         31886        5566534.0    65.0         1
Name: count, Length: 843, dtype: int64

-> agg function means you can apply sum/mean/mode all these function multiple times over data

In [29]:
# apply aggregation function over multiple columns 
genre = data.groupby('Genre').max()

In [30]:
genre

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

In [33]:
genres = data.groupby('Genre')

-> This function is used for applying multiple commands using single funciton

In [43]:
genres.agg(
    {
        'Released_Year': 'mean',
        'Runtime' : 'max',
        'IMDB_Rating' : 'max',
        'No_of_Votes' : 'max'
    }
)

           Released_Year  Runtime  IMDB_Rating  No_of_Votes
Genre
Action       1997.081395      321          9.0      2303232
Adventure    1986.450704      228          8.6      1512360
Animation    2002.219512      137          8.6       999790
Biography    1998.386364      209          8.9      1213505
Comedy       1986.554839      188          8.6       939631
Crime        1989.420561      229          9.2      1826188
Drama        1988.948097      242          9.3      2343110
Family       1976.500000      115          7.8       372490
Fantasy      1921.000000       94          8.1        88794
Film-Noir    1944.333333      108          8.1       158731
Horror       1977.818182      122          8.5       787806
Mystery      1986.166667      138          8.4      1129894
Thriller     1967.000000      108          7.8        27733
Western      1968.750000      165          8.8       688390

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   Released_Year  1000 non-null   object
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   object
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object
 6   Star1          1000 non-null   object
 7   No_of_Votes    1000 non-null   int64
 8   Gross          1000 non-null   float64
 9   Metascore      843 non-null    float64
dtypes: float64(3), int64(2), object(5)
memory usage: 78.3+ KB

In [ ]:
print(data['Released_Year'].dtype)
print(data['Released_Year'].unique())

-> .dtype  function

In [39]:
# find the data type of a particular feature
data['Released_Year'].dtype

dtype('O')

In [41]:
data['Released_Year'] = pd.to_numeric(data['Released_Year'], errors='coerce')

In [42]:
data['Released_Year'].dtype

dtype('float64')

In [ ]:
 Series_Title   1000 non-null   object 
 1   Released_Year  1000 non-null   object 
 2   Runtime        1000 non-null   int64  
 3   Genre          1000 non-null   object 
 4   IMDB_Rating    1000 non-null   float64
 5   Director       1000 non-null   object 
 6   Star1          1000 non-null   object 
 7   No_of_Votes    1000 non-null   int64  
 8   Gross          1000 non-null   float64
 9   Metascore

In [64]:
data2 = pd.read_csv('movies.csv')

-> Use only particular column from the datasets

In [65]:
data2 = data2[['Released_Year','Runtime','IMDB_Rating','No_of_Votes','Gross','Genre']]

In [66]:
data2.head()

  Released_Year  Runtime  IMDB_Rating  No_of_Votes        Gross   Genre
0          1994      142          9.3      2343110   28341469.0   Drama
1          1972      175          9.2      1620367  134966411.0   Crime
2          2008      152          9.0      2303232  534858444.0  Action
3          1974      202          9.0      1129952   57300000.0   Crime
4          1957       96          9.0       689845    4360000.0   Crime

In [67]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Released_Year  1000 non-null   object
 1   Runtime        1000 non-null   int64
 2   IMDB_Rating    1000 non-null   float64
 3   No_of_Votes    1000 non-null   int64
 4   Gross          1000 non-null   float64
 5   Genre          1000 non-null   object
dtypes: float64(2), int64(2), object(2)
memory usage: 47.0+ KB

In [68]:
data2['Released_Year'] = pd.to_numeric(data2['Released_Year'], errors='coerce')

In [69]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Released_Year  999 non-null    float64
 1   Runtime        1000 non-null   int64
 2   IMDB_Rating    1000 non-null   float64
 3   No_of_Votes    1000 non-null   int64
 4   Gross          1000 non-null   float64
 5   Genre          1000 non-null   object
dtypes: float64(3), int64(2), object(1)
memory usage: 47.0+ KB

In [70]:
genres2 = data2.groupby('Genre')

In [75]:
# find the min,max,median of the Genre feature for its all categories
genres2.agg(['min','max','median'])

          Released_Year                 Runtime             IMDB_Rating       \
                    min     max  median     min  max median         min  max
Genre
Action           1924.0  2019.0  2004.0      45  321  127.5         7.6  9.0
Adventure        1925.0  2019.0  1990.0      88  228  127.0         7.6  8.6
Animation        1940.0  2020.0  2004.0      71  137   99.5         7.6  8.6
Biography        1928.0  2020.0  2004.0      93  209  129.0         7.6  8.9
Comedy           1921.0  2020.0  1993.0      68  188  106.0         7.6  8.6
Crime            1931.0  2019.0  1996.0      80  229  122.0         7.6  9.2
Drama            1925.0  2020.0  1997.0      64  242  121.0         7.6  9.3
Family           1971.0  1982.0  1976.5     100  115  107.5         7.8  7.8
Fantasy          1920.0  1922.0  1921.0      76   94   85.0         7.9  8.1
Film-Noir        1941.0  1949.0  1943.0     100  108  104.0         7.8  8.1
Horror           1933.0  2017.0  1978.0      71  122  103.0         7.6  8.5
Mystery          1938.0  2012.0  1996.0      96  138  117.5         7.6  8.4
Thriller         1967.0  1967.0  1967.0     108  108  108.0         7.8  7.8
Western          1965.0  1976.0  1967.0     132  165  148.0         7.8  8.8

                 No_of_Votes                           Gross               \
          median         min      max    median          min          max
Genre
Action       7.9       25312  2303232  275497.0       3296.0  936662225.0
Adventure    7.9       29999  1512360  236060.5      61001.0  874211619.0
Animation    7.9       25229   999790  169246.0     128985.0  873839108.0
Biography    7.9       27254  1213505  188676.5      21877.0  753585104.0
Comedy       7.9       26337   939631   88511.0       1305.0  886752933.0
Crime        8.0       27712  1826188  142107.0       6013.0  790482117.0
Drama        8.0       25088  2343110   86525.0       3600.0  924558264.0
Family       7.8      178731   372490  275610.5    4000000.0  435110554.0
Fantasy      8.0       57428    88794   73111.0  337574718.0  445151978.0
Film-Noir    8.0       59556   158731  148928.0     449191.0  123353292.0
Horror       7.8       27007   787806  362393.0      89029.0  298791505.0
Mystery      8.0       33982  1129894  159514.0    1035953.0  474203697.0
Thriller     7.8       27733    27733   27733.0   17550741.0   17550741.0
Western      8.4       65659   688390  267808.0    5321508.0   31800000.0


                median
Genre
Action     103858027.5
Adventure   57160627.0
Animation  145219819.0
Biography   51710054.0
Comedy      19516000.0
Crime       16290476.0
Drama       18500194.0
Family     219555277.0
Fantasy    391363348.0
Film-Noir    2108060.0
Horror      56000369.0
Mystery     31154590.0
Thriller    17550741.0
Western     10550000.0

In [81]:
df = pd.DataFrame(columns=data.columns)  # creating an empty DataFrame
for group,date in genres:
    df = pd.concat([df, date[date['IMDB_Rating'] == date['IMDB_Rating'].max()]])

C:\Users\dspri\AppData\Local\Temp\ipykernel_11824\897752202.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, date[date['IMDB_Rating'] == date['IMDB_Rating'].max()]])

In [82]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008.0,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
21,Interstellar,2014.0,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
23,Sen to Chihiro no kamikakushi,2001.0,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
7,Schindler's List,1993.0,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
19,Gisaengchung,2019.0,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
26,La vita è bella,1997.0,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
1,The Godfather,1972.0,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
0,The Shawshank Redemption,1994.0,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
688,E.T. the Extra-Terrestrial,1982.0,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
698,Willy Wonka & the Chocolate Factory,1971.0,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920.0,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
309,The Third Man,1949.0,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
49,Psycho,1960.0,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
69,Memento,2000.0,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954.0,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
700,Wait Until Dark,1967.0,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966.0,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

-> split (apply) combine technique

In [83]:
# it goes in every column and find the minimum value for each category
genres.apply(min)

C:\Users\dspri\AppData\Local\Temp\ipykernel_11824\1443917609.py:1: FutureWarning: The provided callable <built-in function min> is currently using np.minimum.reduce. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.minimum.reduce instead.
  genres.apply(min)
C:\Users\dspri\AppData\Local\Temp\ipykernel_11824\1443917609.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(min)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,,
Action,300,1924.0,45,Action,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,NaN
Adventure,2001: A Space Odyssey,NaN,88,Adventure,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,NaN
Animation,Akira,1940.0,71,Animation,7.6,Adam Elliot,Adrian Molina,25229,128985.0,NaN
Biography,12 Years a Slave,1928.0,93,Biography,7.6,Adam McKay,Adrien Brody,27254,21877.0,NaN
Comedy,(500) Days of Summer,1921.0,68,Comedy,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,NaN
Crime,12 Angry Men,1931.0,80,Crime,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,NaN
Drama,1917,1925.0,64,Drama,7.6,Aamir Khan,Abhay Deol,25088,3600.0,NaN
Family,E.T. the Extra-Terrestrial,1971.0,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920.0,76,Fantasy,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941.0,100,Film-Noir,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933.0,71,Horror,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938.0,96,Mystery,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,NaN
Thriller,Wait Until Dark,1967.0,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965.0,132,Western,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [86]:
# find the number of movies start with A in each genres of group
df = pd.DataFrame(columns=data.columns)  # creating an empty DataFrame
for group,date in genres:
    df = pd.concat([df, date[date['Series_Title'].str[0] == 'A']])

C:\Users\dspri\AppData\Local\Temp\ipykernel_11824\951259526.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, date[date['Series_Title'].str[0] == 'A']])

In [87]:
df

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
59,Avengers: Endgame,2019.0,181,Action,8.4,Anthony Russo,Joe Russo,809955,858373000.0,78.0
60,Avengers: Infinity War,2018.0,149,Action,8.4,Anthony Russo,Joe Russo,834477,678815482.0,68.0
106,Aliens,1986.0,137,Action,8.3,James Cameron,Sigourney Weaver,652719,85160248.0,84.0
166,Andaz Apna Apna,1994.0,160,Action,8.2,Rajkumar Santoshi,Aamir Khan,49300,213351844.0,NaN
224,A Wednesday,2008.0,104,Action,8.1,Neeraj Pandey,Anupam Kher,73891,573329738.0,NaN
...,...,...,...,...,...,...,...,...,...,...
804,Abre los ojos,1997.0,119,Drama,7.7,Alejandro Amenábar,Eduardo Noriega,64082,368234.0,NaN
813,A Little Princess,1995.0,97,Drama,7.7,Alfonso Cuarón,Liesel Matthews,32236,10019307.0,83.0
824,A Few Good Men,1992.0,138,Drama,7.7,Rob Reiner,Tom Cruise,235388,141340178.0,62.0
903,A Star Is Born,2018.0,136,Drama,7.6,Bradley Cooper,Lady Gaga,334312,215288866.0,88.0
75,Alien,1979.0,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0

In [ ]:
# find the ranking of each movie based